In [14]:
from numba import njit
import numpy as np

arr_card_on_board = [61,72,268]
arr_card_on_hand_1 = [4,5,7,24,32,33,37,46]
@njit()
def check_join_sets(arr_card_on_board,arr_card_on_hand_1):
   arr_card_join = []
   for k_ in arr_card_on_hand_1:
      natural_parts = int(k_//13)
      for idx_ in arr_card_on_board:
         if idx_ < 44:
            natural_parts_run = int(idx_//11)
            if natural_parts_run == natural_parts:    #cùng chất
               if (k_%13)-(idx_%11)==3 or (idx_%11)-(k_%13)==1:   # nối dây
                  arr_card_join.append([k_,idx_])
         if 44 <= idx_ < 84:
            natural_parts_run = int((idx_-44)//10)
            if natural_parts_run == natural_parts:    
               if (k_%13)-((idx_-44)%10)==4 or ((idx_-44)%10)-(k_%13)==1: 
                  arr_card_join.append([k_,idx_])
         if 84 <= idx_ < 120:
            natural_parts_run = int((idx_-84)//9)
            if natural_parts_run == natural_parts: 
               if (k_%13)-((idx_-84)%9)==5 or ((idx_-84)%9)-(k_%13)==1:
                  arr_card_join.append([k_,idx_])
         if 120 <= idx_ < 152:
            natural_parts_run = int((idx_-120)//8)
            if natural_parts_run == natural_parts: 
               if (k_%13)-((idx_-120)%8)==6 or ((idx_-120)%8)-(k_%13)==1:
                  arr_card_join.append([k_,idx_])
         if 152 <= idx_ < 180:
            natural_parts_run = int((idx_-152)//7)
            if natural_parts_run == natural_parts:
               if (k_%13)-((idx_-152)%7)==7 or ((idx_-152)%7)-(k_%13)==1:
                  arr_card_join.append([k_,idx_])
         if 180 <= idx_ < 204:
            continue
         if 204 <= idx_ < 256:
            if (k_%13) == int((idx_-204)//4):
               arr_card_join.append([k_,idx_])
         if 256 <= idx_ < 269:
            continue
   if len(arr_card_join) == 0:
      arr_card_join = np.full((0,2),0)
      return arr_card_join
   else:
      return np.array(arr_card_join)
arr_card_join = check_join_sets(arr_card_on_board,arr_card_on_hand_1)
print(arr_card_join)

c:\Python\Python310\lib\site-packages\numba\core\ir_utils.py:2147: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'arr_card_on_board' of function 'check_join_sets'.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "..\..\..\AppData\Local\Temp\ipykernel_4344\81444435.py", line 6:
<source missing, REPL/exec in use?>

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
c:\Python\Python310\lib\site-packages\numba\core\ir_utils.py:2147: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'arr_card_on_hand_1' of function 'check_join_sets'.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "..\..\..\AppData\Loca

[[24 61]
 [33 72]]


In [45]:
from numba import njit
import numpy as np
arr = np.array([45,46,47,48])
@njit()
def straight_subsequences(arr):
   arr_return = []
   n = len(arr)
   for k in range(3,8):
      if n < k:
         arr_return = np.full((0,2),0)
         return arr_return
      
      for i in range(0, n-k+1):
         sub_arr = arr[i:i+k]
         if (np.max(sub_arr) - np.min(sub_arr) == k-1) and (int(sub_arr[0]//13) == int(sub_arr[k-1]//13)):
            arr_return.append([sub_arr[0], k])
            print(arr_return)
   print(arr_return)
   if len(arr_return) == 0:
      arr_return = np.full((0,2),0)
      return arr_return
   else:
      return np.array(arr_return)

straight_subsequences_arr = straight_subsequences(arr)
print(straight_subsequences_arr)

[[45, 3]]
[[45, 3], [46, 3]]
[[45, 3], [46, 3], [45, 4]]
[]


In [31]:
env_state = np.array([28, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 21, 13, 24, 0, 34, 32, 51, 4, 23, 35, 25, 11, 6, 41, 40, 38, 50, 33, 43, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 
0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 41, 3, 52, 41, 39, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
print("Các thẻ trên tay người số 0:",np.where(env_state[109:161]==1)[0])
print("Các bộ đã đánh ra ngoài:", np.where(env_state[331:600]==1)[0])


Các thẻ trên tay người số 0: [ 1  3  8 10 12 20 29 30]
Các bộ đã đánh ra ngoài: [ 40 226]


In [64]:
import numpy as np
a = [1,2,3,4]
print(a[0:0])


[]


In [37]:
import numpy as np
def weighted_random(arr_card_on_board):
   """Trả ra index"""
   sum_ = np.sum(arr_card_on_board)
   if sum_ <= 1e-15:
      raise

   rand_card = np.random.uniform(0, sum_)
   for idx_card in range(arr_card_on_board.shape[0]):
      rand_card -= arr_card_on_board[idx_card]
      if rand_card <= 0:
         return idx_card

def step():
   arr_card_on_board = np.array([32,32,32,32,32,32,32,32,32,128])
   idx = weighted_random(arr_card_on_board)
   return idx
step()


9

In [65]:
from numba import njit,jit 
import numpy as np
@njit()
def pick_card_upside_dow(arr_2):
   pick_upside_dow = np.where(arr_2 != -1)[0]
   arr_pick_upside_dow = arr_2[0:(pick_upside_dow[-1]+1)]
   print(pick_upside_dow)
   print(pick_upside_dow[-1])
   return arr_pick_upside_dow

arr_2 = np.array([-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1])
arr_pick_upside_dow = pick_card_upside_dow(arr_2)  #arr vị trí
print(arr_pick_upside_dow[-1])
# print(len(arr_pick_upside_dow))
# print(arr_pick_upside_dow[-1])

# card_choose = arr_pick_upside_dow[-1]
# env_state[51+len(arr_pick_upside_dow)] = -1
# env_state[109+card_choose] = 1
# arr_card_player = env_state[109:161]


[]
0
-1


In [63]:
from numba import njit,jit 
import numpy as np
@njit()
def pick_card_upside_dow(arr_2):
   pick_upside_dow = np.where(arr_2 != -1)[0]
   arr_pick_upside_dow = arr_2[0:len(pick_upside_dow)]
   return arr_pick_upside_dow

arr_2 = np.array([-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1 ,-1, -1 ,-1 ,-1 ,-1])
arr_pick_upside_dow = pick_card_upside_dow(arr_2)  #arr vị trí
print(arr_pick_upside_dow)
print(len(arr_pick_upside_dow))
card_choose = arr_pick_upside_dow[-1]
print(card_choose)
# env_state[51+len(arr_pick_upside_dow)] = -1
# env_state[109+card_choose] = 1
# arr_card_player = env_state[109:161]


[]
0


IndexError: index -1 is out of bounds for axis 0 with size 0

In [53]:
%timeit check()

449 ns ± 37.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
import numpy as np
temp = np.arange(52)
np.random.shuffle(temp)
print(temp)


[35 24 50  9 22 20  4 10  1 27 33 16 26 18 17  8 11 32 29 23 45  5 14  3
 30 40 21 48 19 51 37 25 39 42 34 46  7 49 36 15 31  2  0 43  6 12 47 28
 38 41 44 13]


In [1]:
import numpy as np
def visualizeEnv(env_state):
   dict_ = {}
   dict_["Bài úp trên bàn:"] = np.where(env_state[0:52] != -1)[0]
   dict_["Bài ngửa trên bàn:"] = env_state[52:(52+len(np.where(env_state[52:104] != -1)[0]))]
   dict_["Bài trên tay người thứ nhất:"] = np.where(env_state[109:161]==1)[0]
   dict_["Bài trên tay người thứ hai:"] = np.where(env_state[161:213]==1)[0]
   dict_["Bài trên tay người thứ ba:"] = np.where(env_state[213:265]==1)[0]
   dict_["Bài trên tay người thứ tư:"] = np.where(env_state[265:]==1)[0]
   dict_["Người số mấy đang chơi:"] = env_state[104]
   dict_["Điểm ván nhỏ:"] = env_state[327:331]
   dict_["Người còn lại trong bàn chơi:"] = env_state[321:325]
   dict_["Các bộ đã được đánh ra:"] = np.where(env_state[331:600]==1)[0]
   dict_["turn"] = env_state[325]

   return dict_

In [7]:
import numpy as np
env_state = np.full(8,0)
env_state[0:4] = [0,0,0,0]
env_state[4:8] = [64,0,54,0]

arr_status_player = np.where(env_state[0:4] == 1)[0]
check_win_arr = env_state[4+arr_status_player]
print(check_win_arr)
min_point = np.min(check_win_arr)
arr_winner = np.where(check_win_arr == min_point)[0]
print(arr_winner)


[]


ValueError: zero-size array to reduction operation minimum which has no identity

In [8]:
import numpy as np
P_id = 4
asd = [0,1,2,3,4,5,6]
add = np.full(len(asd),4)
c = asd+add
a = []
for i in range(len(c)):
   if c[i] > 6:
      c[i] -= 7
b = np.min(c)
print(len(asd))
print(c)
print(b)
   


7
[4 5 6 0 1 2 3]
0


In [13]:
import numpy as np

def reset():
    env_state = np.zeros(909)
    deal_card = np.zeros(416)


    for i in range(9):
        deal_card[32*i:32*(i+1)] = 1 + i
    
    deal_card[288:416] = 10
    np.random.shuffle(deal_card)

    env_state[:416] = deal_card

    # env_state[832:839] = số tiền từng người
    # env_state[839:909] = lá bài trên tay người chơi
    # env_state[909] = người đang chơi


    return env_state

reset()


array([ 1.,  9.,  5., 10.,  8.,  6., 10.,  8.,  3.,  8.,  2.,  8.,  4.,
       10.,  2.,  7.,  7.,  8.,  4.,  2.,  1.,  4., 10.,  8.,  5.,  1.,
        1., 10.,  4.,  2.,  3., 10., 10.,  5.,  3., 10., 10.,  8., 10.,
        3.,  7.,  9.,  1., 10.,  7.,  3.,  8., 10.,  8., 10.,  6.,  2.,
        8., 10.,  7., 10.,  2.,  4.,  7., 10., 10., 10.,  7., 10.,  9.,
       10.,  2.,  2., 10.,  6., 10.,  1.,  7.,  3., 10.,  2.,  3., 10.,
        3.,  8., 10.,  8.,  4.,  7.,  2.,  7.,  6., 10.,  1., 10.,  9.,
        2.,  6.,  5.,  5., 10.,  8.,  2., 10.,  7., 10.,  5.,  5.,  9.,
       10., 10.,  9., 10.,  8., 10.,  5.,  2., 10., 10., 10.,  1., 10.,
        1., 10.,  3., 10., 10.,  7.,  9.,  9.,  3., 10.,  1.,  9.,  3.,
        8., 10., 10.,  6.,  8.,  4., 10.,  9.,  7.,  4.,  2.,  1.,  6.,
        4.,  9.,  4.,  6.,  9., 10.,  1.,  1.,  8., 10.,  3.,  8.,  6.,
        4.,  3., 10., 10.,  6., 10., 10.,  4.,  9.,  2.,  8., 10.,  8.,
        2.,  2.,  2., 10., 10.,  5., 10., 10.,  4.,  6., 10.,  3

In [6]:
def get_player_state(env_state):
    
    P_state = np.zeros()
    P_state[:416] = env_state[416:832]
    P_state[416] = env_state[909]
    for ii in range(7):
        ID_other = env_state[909] + ii
        if ID_other <= 6:
            P_state[(417+ii)] = env_state[832 + ID_other]
        else:
            add_kc = 2*(ID_other - 7)
            P_state[417+ii] = env_state[839 -  ID_other + add_kc]

    

    return P_state.astype(np.float64)


In [1]:
import numpy as np

def reset():

    env_state = np.zeros(40)
    number_of_card = np.zeros(10)

    number_of_card[0:9] = 32
    number_of_card[9] = 128

    env_state[0:10] = number_of_card[:10]
    
    # env_state[20:27] = số tiền của từng người
    # env_state[27:49] = lá bài trên tay người chơi(max)
    # env_state[49] = ID_player
    
    return env_state
reset()

array([ 32.,  32.,  32.,  32.,  32.,  32.,  32.,  32.,  32., 128.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [48]:
import numpy as np
def weighted_Random():
    arr = [32,32,32,32,32,32,32,32,32,128]
    c = np.sum(arr)
    d = np.random.uniform(0,c)
    for id in range(len(arr)):
        e = d - arr[id]
        if e <= 0:
            print(id)
weighted_Random()


9


In [3]:
import numpy as np
def initEnv():

    env_state = np.zeros(198)
    env_state[:9] = 32
    env_state[9] = 128
    env_state[10] = 10000
    env_state[11:17] = 1000
 
    return env_state
    
env_state = initEnv()

In [4]:
def getAgentState(env_state):

    P_state = np.zeros(150)
    P_id = env_state[43]//2
    P1_id = env_state[43]
    for i in range(7):
        if (P_id+i) <= 6:
            P_state[i] = env_state[10+P_id+i]
        elif (P_id+i) > 6:
            P_state[i] = env_state[3+P_id+i]
    for lct in range(7):
        if (P_id+lct) <= 6:
            P_state[(7+20*lct):(7+20*(lct+1))] = env_state[(44+(P_id+lct)*22):(44+(P_id+lct+1)*22)]
        elif (P_id+lct) > 6:
            P_state[(7+20*lct):(7+20*(lct+1))] = env_state[(44+(P_id+lct-7)*22):(44+(P_id+lct-6)*22)]

    P_state[149] = env_state[198]

    return P_state.astype(np.float64)


In [5]:
def getValidActions(P_state):
    Valid_Actions_return = np.zeros()
    Check_place_a_bet = P_state[147]
    Check_coin_player = P_state[:7]
    Card_on_hand = P_state[7:27]
    Coin_a_bet = P_state[148]
    Sum_number_of_card = np.sum(Card_on_hand)

    if Check_place_a_bet == 0:
        if Check_coin_player[0] >= 100:
            Valid_Actions_return[0:4] = 1
        elif Check_coin_player[0]<100 and Check_coin_player[0]>=25:
            Valid_Actions_return[0:3] = 1
            Valid_Actions_return[3] = 0
        elif Check_coin_player[0]<25 and Check_coin_player[0]>=10:
            Valid_Actions_return[0:2] = 1
            Valid_Actions_return[2:4] = 0
        elif Check_coin_player[0]<10 and Check_coin_player[0]>=5:
            Valid_Actions_return[0] = 1
            Valid_Actions_return[1:4] = 0
        elif Check_coin_player[0]<5:
            Valid_Actions_return[0:4] = 0
    elif Check_place_a_bet == 1:
        card_other_0 = 0
        for run in range(len(Card_on_hand)):
            if run != 0:
                card_other_0 += 1
        if card_other_0==1 and Sum_number_of_card==2:
            if Check_coin_player >= Coin_a_bet:
                Valid_Actions_return[4:8] = 1
        elif card_other_0!=1 and Sum_number_of_card==2:
            if Check_coin_player >= Coin_a_bet:
                Valid_Actions_return[4:7] = 1
                Valid_Actions_return[7] = 0
        else: 
            Valid_Actions_return[4:6] = 1
            Valid_Actions_return[6:8] = 0
            
    return Valid_Actions_return